### ISSUE TITLE
1.21.4 does not work with SNMP

### ISSUE THREAD

**Issue by fatalbyte** [influxdata/telegraf#10674]
### Relevant telegraf.conf

```toml
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})


# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"


# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "Âµs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  # debug = false
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  logfile = "/var/log/telegraf/telegraf.log"

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  # urls = ["udp://127.0.0.1:8089"]
  urls = ["http://127.0.0.1:8086"]

  ## The target database for metrics; will be created as needed.
  ## For UDP url endpoint database needs to be configured on server side.
  database = "telegraf"

  ## The value of this tag will be used to determine the database.  If this
  ## tag is not set the 'database' option is used as the default.
  # database_tag = ""

  ## If true, the 'database_tag' will not be included in the written metric.
  # exclude_database_tag = false

  ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
  ## Telegraf with a user without permissions to create databases or when the
  ## database already exists.
  # skip_database_creation = false

  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.  Only takes effect when using HTTP.
  # retention_policy = ""

  ## The value of this tag will be used to determine the retention policy.  If this
  ## tag is not set the 'retention_policy' option is used as the default.
  # retention_policy_tag = ""

  ## If true, the 'retention_policy_tag' will not be included in the written metric.
  # exclude_retention_policy_tag = false

  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all".
  ## Only takes effect when using HTTP.
  # write_consistency = "any"

  ## Timeout for HTTP messages.
  # timeout = "5s"

  ## HTTP Basic Auth
  username = "telegraf"
  password = "<password here>"

  ## HTTP User-Agent
  # user_agent = "telegraf"

  ## UDP payload size is the maximum packet size to send.
  # udp_payload = "512B"

  ## Optional TLS Config for use on HTTP connections.
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## HTTP Proxy override, if unset values the standard proxy environment
  ## variables are consulted to determine which proxy, if any, should be used.
  # http_proxy = "http://corporate.proxy:3128"

  ## Additional HTTP headers
  # http_headers = {"X-Special-Header" = "Special-Value"}

  ## HTTP Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
  # content_encoding = "gzip"

  ## When true, Telegraf will output unsigned integers as unsigned values,
  ## i.e.: "42u".  You will need a version of InfluxDB supporting unsigned
  ## integer values.  Enabling this option will result in field type errors if
  ## existing data has been written.
  # influx_uint_support = false

```
Everything below here is the standard config file.  Was not able to post entire config in bug report.

### Logs from Telegraf

> 2022-02-17T18:06:14Z I! [agent] Hang on, flushing any cached metrics before shutdown
> 2022-02-17T18:06:14Z I! [agent] Stopping running outputs
> 2022-02-17T18:06:20Z I! Loaded inputs: cpu disk diskio exec (2x) file kernel mem net netstat ping (2x) processes snmp (8x) swap system
> 2022-02-17T18:06:20Z I! Loaded aggregators: 
> 2022-02-17T18:06:20Z I! Loaded processors: 
> 2022-02-17T18:06:20Z I! Loaded outputs: influxdb
> 2022-02-17T18:06:20Z I! Tags enabled: host=raspberrypi
> 2022-02-17T18:06:20Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"raspberrypi", Flush Interval:10s
> 2022-02-17T18:06:33Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:06:33Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:06:56Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field hostname: translating: cannot make RFC1213-MIB::sysName.0 numeric, please ensure all imported mibs are in the path
> 2022-02-17T18:06:56Z I! Loaded inputs: cpu disk diskio exec (2x) file kernel mem net netstat ping (2x) processes snmp (8x) swap system
> 2022-02-17T18:06:56Z I! Loaded aggregators: 
> 2022-02-17T18:06:56Z I! Loaded processors: 
> 2022-02-17T18:06:56Z I! Loaded outputs: influxdb
> 2022-02-17T18:06:56Z I! Tags enabled: host=raspberrypi
> 2022-02-17T18:06:56Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"raspberrypi", Flush Interval:10s
> 2022-02-17T18:07:10Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:07:10Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:07:32Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field hostname: translating: cannot make RFC1213-MIB::sysName.0 numeric, please ensure all imported mibs are in the path
> 2022-02-17T18:07:32Z I! Loaded inputs: cpu disk diskio exec (2x) file kernel mem net netstat ping (2x) processes snmp (8x) swap system
> 2022-02-17T18:07:32Z I! Loaded aggregators: 
> 2022-02-17T18:07:32Z I! Loaded processors: 
> 2022-02-17T18:07:32Z I! Loaded outputs: influxdb
> 2022-02-17T18:07:32Z I! Tags enabled: host=raspberrypi
> 2022-02-17T18:07:32Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"raspberrypi", Flush Interval:10s
> 2022-02-17T18:07:46Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:07:46Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:08:09Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field hostname: translating: cannot make RFC1213-MIB::sysName.0 numeric, please ensure all imported mibs are in the path
> 2022-02-17T18:08:09Z I! Loaded inputs: cpu disk diskio exec (2x) file kernel mem net netstat ping (2x) processes snmp (8x) swap system
> 2022-02-17T18:08:09Z I! Loaded aggregators: 
> 2022-02-17T18:08:09Z I! Loaded processors: 
> 2022-02-17T18:08:09Z I! Loaded outputs: influxdb
> 2022-02-17T18:08:09Z I! Tags enabled: host=raspberrypi
> 2022-02-17T18:08:09Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"raspberrypi", Flush Interval:10s
> 2022-02-17T18:08:22Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:08:22Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:08:44Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field hostname: translating: cannot make RFC1213-MIB::sysName.0 numeric, please ensure all imported mibs are in the path
> 2022-02-17T18:08:51Z I! Loaded inputs: cpu disk diskio exec (2x) file kernel mem net netstat ping (2x) processes snmp (8x) swap system
> 2022-02-17T18:08:51Z I! Loaded aggregators: 
> 2022-02-17T18:08:51Z I! Loaded processors: 
> 2022-02-17T18:08:51Z I! Loaded outputs: influxdb
> 2022-02-17T18:08:51Z I! Tags enabled: host=raspberrypi
> 2022-02-17T18:08:51Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"raspberrypi", Flush Interval:10s

### System info

Telegraf 1.20.4, Raspbian GNU/Linux 10 (buster)

### Steps to reproduce

1. Install Telegraf 1.21.4
2. Run telegraf --test --config <configfile>.conf
3. See errors related above
...

### Expected behavior

```
telegraf --test --config <configfile>.conf 
2022-02-17T18:09:12Z I! Starting Telegraf 1.20.4
> snmp,agent_host=<data>
```
### Actual behavior

> 2022-02-17T18:07:28Z I! Starting Telegraf 1.21.4
> 2022-02-17T18:07:28Z I! Loaded inputs: snmp
> 2022-02-17T18:07:28Z I! Loaded aggregators: 
> 2022-02-17T18:07:28Z I! Loaded processors: 
> 2022-02-17T18:07:28Z W! Outputs are not used in testing mode!
> 2022-02-17T18:07:28Z I! Tags enabled: host=raspberrypi
> r^H2022-02-17T18:07:41Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:07:41Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
> 2022-02-17T18:08:04Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field hostname: translating: cannot make RFC1213-MIB::sysName.0 numeric, please ensure all imported mibs are in the path

### Additional info

1.21.4 does not work with SNMP, but 1.20.4 works perfectly.  Would like to have this fixed so that I may upgrade to the latest version of Telegraf.  Anyone else having this issue?  Anyone have a fix?

**Comment by MyaLongmire** [comment]
Thank you for reporting this! The way telegraf is trying to follow symlinks to load in folders has a bug on windows and we are looking into it. I will let you know when there is a pr up with a fix :)

**Comment by MyaLongmire** [comment]
Oh sorry about that, the bot labeled it as windows. Can you post the snmp part of your config?

**Comment by fatalbyte** [comment]
> Oh sorry about that, the bot labeled it as windows. Can you post the snmp part of your config?

Hi Mya, is this what you need?

# # DEPRECATED! PLEASE USE inputs.snmp INSTEAD.
# [[inputs.snmp_legacy]]
#   ## Use 'oids.txt' file to translate oids to names
#   ## To generate 'oids.txt' you need to run:
#   ##   snmptranslate -m all -Tz -On | sed -e 's/"//g' > /tmp/oids.txt
#   ## Or if you have an other MIB folder with custom MIBs
#   ##   snmptranslate -M /mycustommibfolder -Tz -On -m all | sed -e 's/"//g' > oids.txt
#   snmptranslate_file = "/tmp/oids.txt"
#   [[inputs.snmp.host]]
#     address = "192.168.2.2:161"
#     # SNMP community
#     community = "public" # default public
#     # SNMP version (1, 2 or 3)
#     # Version 3 not supported yet
#     version = 2 # default 2
#     # SNMP response timeout
#     timeout = 2.0 # default 2.0
#     # SNMP request retries
#     retries = 2 # default 2
#     # Which get/bulk do you want to collect for this host
#     collect = ["mybulk", "sysservices", "sysdescr"]
#     # Simple list of OIDs to get, in addition to "collect"
#     get_oids = []
#
#   [[inputs.snmp.host]]
#     address = "192.168.2.3:161"
#     community = "public"
#     version = 2
#     timeout = 2.0
#     retries = 2
#     collect = ["mybulk"]
#     get_oids = [
#         "ifNumber",
#         ".1.3.6.1.2.1.1.3.0",
#     ]
#
#   [[inputs.snmp.get]]
#     name = "ifnumber"
#     oid = "ifNumber"
#
#   [[inputs.snmp.get]]
#     name = "interface_speed"
#     oid = "ifSpeed"
#     instance = "0"
#
#   [[inputs.snmp.get]]
#     name = "sysuptime"
#     oid = ".1.3.6.1.2.1.1.3.0"
#     unit = "second"
#
#   [[inputs.snmp.bulk]]
#     name = "mybulk"
#     max_repetition = 127
#     oid = ".1.3.6.1.2.1.1"
#
#   [[inputs.snmp.bulk]]
#     name = "ifoutoctets"
#     max_repetition = 127
#     oid = "ifOutOctets"
#
#   [[inputs.snmp.host]]
#     address = "192.168.2.13:161"
#     #address = "127.0.0.1:161"
#     community = "public"
#     version = 2
#     timeout = 2.0
#     retries = 2
#     #collect = ["mybulk", "sysservices", "sysdescr", "systype"]
#     collect = ["sysuptime" ]
#     [[inputs.snmp.host.table]]
#       name = "iftable3"
#       include_instances = ["enp5s0", "eth1"]
#
#   # SNMP TABLEs
#   # table without mapping neither subtables
#   [[inputs.snmp.table]]
#     name = "iftable1"
#     oid = ".1.3.6.1.2.1.31.1.1.1"
#
#   # table without mapping but with subtables
#   [[inputs.snmp.table]]
#     name = "iftable2"
#     oid = ".1.3.6.1.2.1.31.1.1.1"
#     sub_tables = [".1.3.6.1.2.1.2.2.1.13"]
#
#   # table with mapping but without subtables
#   [[inputs.snmp.table]]
#     name = "iftable3"
#     oid = ".1.3.6.1.2.1.31.1.1.1"
#     # if empty. get all instances
#     mapping_table = ".1.3.6.1.2.1.31.1.1.1.1"
#     # if empty, get all subtables
#
#   # table with both mapping and subtables
#   [[inputs.snmp.table]]
#     name = "iftable4"
#     oid = ".1.3.6.1.2.1.31.1.1.1"
#     # if empty get all instances
#     mapping_table = ".1.3.6.1.2.1.31.1.1.1.1"
#     # if empty get all subtables
#     # sub_tables could be not "real subtables"
#     sub_tables=[".1.3.6.1.2.1.2.2.1.13", "bytes_recv", "bytes_send"]


# # Read stats from one or more Solr servers or cores
# [[inputs.solr]]
#   ## specify a list of one or more Solr servers
#   servers = ["http://localhost:8983"]
#
#   ## specify a list of one or more Solr cores (default - all)
#   # cores = ["main"]
#
#   ## Optional HTTP Basic Auth Credentials
#   # username = "username"
#   # password = "pa$$word"

**Comment by MyaLongmire** [comment]
In that file, the snmp section is commented out. The error you are getting is also with mib `RFC1213-MIB::sysName.0` and in your config I did not find you trying to monitor that mib.

**Comment by fatalbyte** [comment]
Hi Mya, thanks for all the responses. What am I missing in the SNMP part of the config?  And what do I need to do to load the MIBs I have added?  This worked fine on 1.20.4, and stopped working on the very next version. 

I’m using SNMP configs all loaded in /etc/telegraf/telegraf.d

My MIBs live in /usr/share/snmp/mibs

Do you need an example config file to help troubleshoot?

Thanks!

**Comment by Hipska** [comment]
Is the `/usr/share/snmp/mibs` readable by the user that is running telegraf?

And yes, we would like to see relevant part of telegraf config where you define your snmp settings.

**Comment by bondskin** [comment]
same here, and yes /usr/share/snmp/mibs is readable

 [[inputs.snmp.field]]
    is_tag = true
    name = "sysName"
    oid = "RFC1213-MIB::sysName.0"
  #  System vendor OID
  [[inputs.snmp.field]]
    name = "sysObjectID"
    oid = "RFC1213-MIB::sysObjectID.0"
  #  System description
  [[inputs.snmp.field]]
    name = "sysDescr"
    oid = "RFC1213-MIB::sysDescr.0"
  #  System contact
  [[inputs.snmp.field]]
    name = "sysContact"
    oid = "RFC1213-MIB::sysContact.0"
  #  System location
  [[inputs.snmp.field]]
    name = "sysLocation"
    oid = "RFC1213-MIB::sysLocation.0"
  #  System uptime
  [[inputs.snmp.field]]


error in log:
Feb 18 10:32:27 raspberrypidns telegraf[1022]: 2022-02-18T09:32:27Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs
Feb 18 10:32:27 raspberrypidns telegraf[1022]: 2022-02-18T09:32:27Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs

**Comment by fatalbyte** [comment]
> Is the `/usr/share/snmp/mibs` readable by the user that is running telegraf?
> 
> And yes, we would like to see relevant part of telegraf config where you define your snmp settings.

Hi Hipska, the /usr/share/snmp/mibs is owned by root, and the permissions are -rw-r--r--

And the process running telegraf is owned by the telegraf user.

ps aux | grep telegraf
telegraf  6203  0.0  0.0   9376   788 ?        S    08:23   0:00 /usr/bin/ping -c 5 -n -s 16 -i 1 -W 1 -w 10 10.26.83.1
pi        6209  0.0  0.0   7348   528 pts/0    S+   08:23   0:00 grep --color=auto telegraf
telegraf 26526  1.9  1.0 908020 82288 ?        Ssl  Feb17  22:38 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

systemctl status telegraf.service 
â— telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-02-17 13:08:50 EST; 19h ago
     Docs: https://github.com/influxdata/telegraf
 Main PID: 26526 (telegraf)
    Tasks: 16 (limit: 4915)
   CGroup: /system.slice/telegraf.service
           â””â”€26526 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
           

Here is an example of one of my snmp config files for a specific device:
`
## This config file retrieves SNMP values from APC UPS remote agents.
## Last updated on 2022-01-17 by RCH.

## Basic Telegraf Config Options
 [[inputs.snmp]]
   agents = [ "ups.localhost.com" ]
   ## Poll interval
   interval = "60s"
   ## Timeout for each SNMP query.
   timeout = "30s"
   ## Number of retries to attempt within timeout.
   retries = 3
   ## SNMP version, values can be 1, 2, or 3
   version = 2
   ## hostname override
   name_override = "ups"
   ## SNMP community string.
   community = "public"


## APC UPS MIB Basic Data
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"

  [[inputs.snmp.field]]
    name = "model"
    oid = "PowerNet-MIB::upsBasicIdentModel.0"

  [[inputs.snmp.field]]
      name = "name"
      oid = "PowerNet-MIB::upsBasicIdentName.0"

  [[inputs.snmp.field]]
      name = "upsAdvIdentFirmwareRevision"
      oid = "PowerNet-MIB::upsAdvIdentFirmwareRevision.0"

  [[inputs.snmp.field]]
      name = "upsAdvIdentDateOfManufacture"
      oid = "PowerNet-MIB::upsAdvIdentDateOfManufacture.0"
  
  [[inputs.snmp.field]]
      name = "upsAdvIdentSerialNumber"
      oid = "PowerNet-MIB::upsAdvIdentSerialNumber.0"

  [[inputs.snmp.field]]
      name = "upsBasicOutputStatus"
      oid = "PowerNet-MIB::upsBasicOutputStatus.0"


## APC UPS Battery Data
  [[inputs.snmp.field]]
      name = "upsBasicBatteryStatus"
      oid = "PowerNet-MIB::upsBasicBatteryStatus.0"

  [[inputs.snmp.field]]
      name = "upsHighPrecBatteryCapacity"
      oid = "PowerNet-MIB::upsHighPrecBatteryCapacity.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecBatteryTemperature"
      oid = "PowerNet-MIB::upsHighPrecBatteryTemperature.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryRunTimeRemaining"
      oid = "PowerNet-MIB::upsAdvBatteryRunTimeRemaining.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryReplaceIndicator"
      oid = "PowerNet-MIB::upsAdvBatteryReplaceIndicator.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryNumOfBattPacks"
      oid = "PowerNet-MIB::upsAdvBatteryNumOfBattPacks.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryNumOfBadBattPacks"
      oid = "PowerNet-MIB::upsAdvBatteryNumOfBadBattPacks.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryNominalVoltage"
      oid = "PowerNet-MIB::upsAdvBatteryNominalVoltage.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryActualVoltage"
      oid = "PowerNet-MIB::upsAdvBatteryActualVoltage.0"

  [[inputs.snmp.field]]
      name = "upsBasicBatteryTimeOnBattery"
      oid = "PowerNet-MIB::upsBasicBatteryTimeOnBattery.0"


## APC UPS Input Line Data
  [[inputs.snmp.field]]
      name = "upsBasicInputPhase"
      oid = "PowerNet-MIB::upsBasicInputPhase.0"

  [[inputs.snmp.field]]
      name = "upsHighPrecInputLineVoltage"
      oid = "PowerNet-MIB::upsHighPrecInputLineVoltage.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsAdvInputFrequency"
      oid = "PowerNet-MIB::upsAdvInputFrequency.0"


## APC UPS Output Line Data
  [[inputs.snmp.field]]
      name = "upsBasicOutputPhase"
      oid = "PowerNet-MIB::upsBasicOutputPhase.0"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputVoltage"
      oid = "PowerNet-MIB::upsHighPrecOutputVoltage.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsAdvOutputFrequency"
      oid = "PowerNet-MIB::upsAdvOutputFrequency.0"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputLoad"
      oid = "PowerNet-MIB::upsHighPrecOutputLoad.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputCurrent"
      oid = "PowerNet-MIB::upsHighPrecOutputCurrent.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputEfficiency"
      oid = "PowerNet-MIB::upsHighPrecOutputEfficiency.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputEnergyUsage"
      oid = "PowerNet-MIB::upsHighPrecOutputEnergyUsage.0"
      conversion = "float(1)"


## APC UPS Diagnostics Data
  [[inputs.snmp.field]]
      name = "upsAdvTestDiagnosticsResults"
      oid = "PowerNet-MIB::upsAdvTestDiagnosticsResults.0"

  [[inputs.snmp.field]]
      name = "upsAdvTestLastDiagnosticsDate"
      oid = "PowerNet-MIB::upsAdvTestLastDiagnosticsDate.0"

  [[inputs.snmp.field]]
      name = "upsCommStatus"
      oid = "PowerNet-MIB::upsCommStatus.0"


## Network Interface Data
  # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards.
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # IF-MIB::ifXTable contains newer High Capacity (HC) counters that do not overflow as fast for a few of the ifTable counters
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifXTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # EtherLike-MIB::dot3StatsTable contains detailed ethernet-level information about what kind of errors have been logged on an interface (such as FCS error, frame too long, etc)
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "EtherLike-MIB::dot3StatsTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
`
With any of this, is there something I have misconfigured or not set appropriately?  I've troubleshot this quite a bit on my own to resolve it, but I'm at a loss at the moment which is why I have opened this bug report.  I'm assuming there are others with the same issue.  Definitely looking to be better educated about this so that I can also help others.

Thanks!

**Comment by Hipska** [comment]
The config by itself looks good. It seems a problem only related to telegraf (or the Go libraries) being unable to read the mibs directory. Thats why I re-added the `bug` label.

The only problem is that we need to figure out how to reproduce this, so it can be fixed..

**Comment by fatalbyte** [comment]
> The config by itself looks good. It seems a problem only related to telegraf (or the Go libraries) being unable to read the mibs directory. Thats why I re-added the `bug` label.
> 
> The only problem is that we need to figure out how to reproduce this, so it can be fixed..

Hi Hipska, thanks for the response and re-adding the bug label.  Not sure if its an option but I'm happy to jump on a screen share and show exactly what I'm doing and reproduce it?

**Comment by mabnz** [comment]
I'm also seeing this on Ubuntu 1.21.4. Works on 1.21.3. This looks really similar to the last SNMP bug I raised a month ago.

telegraf[921824]: 2022-02-21T01:06:01Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field model: translating: cannot make PowerNet-MIB::upsBasicIdentModel.0 numeric, please ensure all imported mibs are in the path

**Comment by ericjohncarlson** [comment]
I also have this issue, exact same config and errors as those above.  I'm using the repos.influxdata.com/debian repo for bullseye, and I think only 1.21.4 is in the repo definition?

**Comment by bondskin** [comment]
Hi @ericjohncarlson , 

I downgraded manuall
curl -LO -C - https://dl.influxdata.com/telegraf/releases/telegraf_1.21.2-1_armhf.deb
sudo dpkg -i telegraf_1.21.2-1_armhf.deb

However, I even needed to go down to 1.20.4 to fix a race condition because of my Unifi AP SNMP.
So 1.20.4 was the last very good version for me.

**Comment by ericjohncarlson** [comment]
> 

Appreciate the reply.  I downgraded through the .deb as well.  There's really no reason for the repo to only have the latest, especially in situations like this, so hopefully the influx team can include at least a few latest known good releases in the repo for easy selection.

**Comment by Hipska** [comment]
Hi all, could you test with the artefacts built from this PR https://github.com/influxdata/telegraf/pull/10735#issuecomment-1050093047? It might not solve your issue, but it will give us more info on why it isn't loading.

Many thanks.

**Comment by bondskin** [comment]
thanks @Hipska ,

this is the result:
```
Feb 28 11:09:36 raspberrypidns telegraf[4305]: 2022-02-28T10:09:36Z I! Loaded outputs: influxdb prometheus_client
Feb 28 11:09:36 raspberrypidns telegraf[4305]: 2022-02-28T10:09:36Z I! Tags enabled: host=raspberrypidns
Feb 28 11:09:36 raspberrypidns systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Feb 28 11:09:36 raspberrypidns telegraf[4305]: 2022-02-28T10:09:36Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"raspberrypidns", Flush Interval:10s
Feb 28 11:09:37 raspberrypidns telegraf[4305]: 2022-02-28T10:09:37Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs: lstat /usr/share/snmp/mibs/usr/share/snmp/mibs>
Feb 28 11:09:37 raspberrypidns telegraf[4305]: 2022-02-28T10:09:37Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs: lstat /usr/share/snmp/mibs/usr/share/snmp/mibs>
Feb 28 11:09:45 raspberrypidns telegraf[4305]: Parse module: /var/lib/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Feb 28 11:09:45 raspberrypidns telegraf[4305]: 2022-02-28T10:09:45Z W! [inputs.snmp] Couldn't load module DPI20-MIB: Could not load module at DPI20-MIB
Feb 28 11:09:48 raspberrypidns telegraf[4305]: Parse module: /var/lib/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Feb 28 11:09:48 raspberrypidns telegraf[4305]: 2022-02-28T10:09:48Z W! [inputs.snmp] Couldn't load module HPR-MIB: Could not load module at HPR-MIB
~
```

**Comment by Hipska** [comment]
Your output says, it still running..

But I also see that your mibs are actually in `/var/lib/mibs` instead of `/usr/share/snmp/mibs`. What if you configure that path in your snmp config?

**Comment by bondskin** [comment]
> Your output says, it still running..
> 
> But I also see that your mibs are actually in `/var/lib/mibs` instead of `/usr/share/snmp/mibs`. What if you configure that path in your snmp config?

correct, it keeps restarting
"     Active: active (running) since Mon 2022-02-28 11:12:04 CET; 21s ago"

I'll check on the mibs path and will report back

**Comment by reimda** [comment]
#10748 should fix the "Couldn't stat target" log warnings. Could any of you test it? There's a CI build available [here](https://github.com/influxdata/telegraf/pull/10748#issuecomment-1054618938). 

I don't think #10748 will fix the "translating: cannot make X numeric" errors. I'm still trying to reproduce those in order to find a fix.

**Comment by Hipska** [comment]
I think that is just the wrong mib, shouldn't it be `SNMPv2-MIB::sysName.0` instead of `RFC1213-MIB::sysName.0`?

**Comment by reimda** [comment]
> I think that is just the wrong mib, shouldn't it be `SNMPv2-MIB::sysName.0` instead of `RFC1213-MIB::sysName.0`?

RFC1213-MIB is snmp v1. SNMPv2-MIB comes from RFC 3418 which is snmp v2. I understand V2 was designed to be compatible in cases like this.

In practice they resolve to the same thing, at least on my machine which has both mib files under /usr/share/snmp/mibs/ietf:
```
$ snmptranslate -On RFC1213-MIB::sysName.0
.1.3.6.1.2.1.1.5.0
$ snmptranslate -On SNMPv2-MIB::sysName.0
.1.3.6.1.2.1.1.5.0
```

**Comment by Hipska** [comment]
Hmm okay. Anyway the cannot translate error came from a setup that couldn’t load the mib path. So with that in mind, it’s normal it couldn’t translate.

So, to all having this problem, would you want to test [these builds](https://github.com/influxdata/telegraf/pull/10748#issuecomment-1054618938) and inform us of the problem is solved?

**Comment by PiDroid-B** [comment]
Hi,

I have the same problem i think. I post info here after spoken with @powersj 

sample of my log :
```
2022-03-04T10:27:38Z I! Loaded aggregators:
2022-03-04T10:27:38Z I! Loaded processors: regex
2022-03-04T10:27:38Z I! Loaded outputs: influxdb (10x)
2022-03-04T10:27:38Z I! Tags enabled: host=vmmonit
2022-03-04T10:27:38Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"vmmonit", Flush Interval:10s                                              
2022-03-04T10:27:38Z D! [agent] Initializing plugins
2022-03-04T10:27:39Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs                                                                        
2022-03-04T10:27:39Z W! [inputs.snmp] Couldn't stat target /usr/share/snmp/mibs                                                                        
2022-03-04T10:27:39Z W! [inputs.snmp] module miblist.txt could not be loaded                                                                           
2022-03-04T10:27:42Z W! [inputs.snmp] module DPI20-MIB could not be loaded
2022-03-04T10:27:43Z W! [inputs.snmp] module HPR-MIB could not be loaded
2022-03-04T10:27:47Z W! [inputs.snmp] module SNMPv2-PDU could not be loaded
2022-03-04T10:27:48Z W! [inputs.snmp] module TCPIPX-MIB could not be loaded
2022-03-04T10:27:48Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing table Server: initializing field product: translating: cannot make CPQSINFO-MIB::cpqSiProductName numeric, please ensure all imported mibs are in the path      
```


I have several input's files for SNMP. For the according error above, this is the relevant part of one of those files (more detail in [telegraf.conf (historical main conf)](https://github.com/influxdata/telegraf/files/8186605/telegraf.conf.txt) and [inputs.ilo4.snmp.conf](https://github.com/influxdata/telegraf/files/8186546/inputs.ilo4.snmp.conf.txt) )  :
```
  [[inputs.snmp.table]]
    name = "Server"
    inherit_tags = [ "hostname" ]
    [[inputs.snmp.table.field]]
      name = "product"
      oid = "CPQSINFO-MIB::cpqSiProductName"
      #oid = ".1.3.6.1.4.1.232.2.2.4.2"
```
I have other similar files for another devices with other mibs.

`/usr/share/snmp/mibs` contains `CPQSINFO-MIB` in owner root: with 644 (I also tested with telegraf: 644 but no better result)

I tried too the build suggested in the PR #10748 but same problem
```
2022-03-04T14:36:03Z I! Starting Telegraf 1.22.0-09c1fcbb
2022-03-04T14:36:03Z I! Loaded inputs: cpu disk diskio http_listener ipmi_sensor kernel mem mqtt_consumer (2x) net netstat processes snmp (2x) socket_listener swap system
2022-03-04T14:36:03Z I! Loaded aggregators: 
2022-03-04T14:36:03Z I! Loaded processors: regex
2022-03-04T14:36:03Z I! Loaded outputs: influxdb (10x)
2022-03-04T14:36:03Z I! Tags enabled: host=vmmonit
2022-03-04T14:36:03Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"vmmonit", Flush Interval:10s
2022-03-04T14:36:03Z D! [agent] Initializing plugins
2022-03-04T14:36:04Z W! [inputs.snmp] Couldn't load module miblist.txt: Could not load module at miblist.txt
2022-03-04T14:36:08Z W! [inputs.snmp] Couldn't load module DPI20-MIB: Could not load module at DPI20-MIB
2022-03-04T14:36:09Z W! [inputs.snmp] Couldn't load module HPR-MIB: Could not load module at HPR-MIB
2022-03-04T14:36:12Z W! [inputs.snmp] Couldn't load module SNMPv2-PDU: Could not load module at SNMPv2-PDU
2022-03-04T14:36:13Z W! [inputs.snmp] Couldn't load module TCPIPX-MIB: Could not load module at TCPIPX-MIB
2022-03-04T14:36:14Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing table Server: initializing field product: translating: cannot make CPQSINFO-MIB::cpqSiProductName numeric, please ensure all imported mibs are in the path
```

All work find if i downgrade to v1.20.4 ( telegraf_1.20.4-1_amd64.deb ).

I hope it can be help to find a fix.
Thank's

**Comment by bunnyevans** [comment]
I have a similar problem.
MIBS from here: http://www.rtpro.yamaha.co.jp/RT/docs/mib/
Put in here: /usr/local/share/snmp/mibs/

Minimalist config:
[[inputs.snmp]]
   agents = [ "10.0.0.1" ]
   version = 2
   community = "cheese"
   max_repetitions = 10
   name = "snmp.rtx830"
# can't find ifTable without this!
   path = ["/usr/local/share/snmp/mibs"]
   [[inputs.snmp.field]]
     name = "yrhFlashROMSize"
     oid = "YAMAHA-RT-HARDWARE::yrhFlashROMSize.0"


Error:
2022-03-05T00:45:21+09:00 E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field yrhFlashROMSize: translating: cannot make YAMAHA-RT-HARDWARE::yrhFlashROMSize.0 numeric, please ensure all
 imported mibs are in the path


snmpwalk of course, gets the right answers:
YAMAHA-RT-HARDWARE::yrhCpuType.0 = INTEGER: a38x(16)
YAMAHA-RT-HARDWARE::yrhMemorySize.0 = INTEGER: 268435456
YAMAHA-RT-HARDWARE::yrhFlashROMSize.0 = INTEGER: 33554432

1.12.4 blows a gasket on whichever one is first in the yamaha-rt-hardware mib.

Dumb thought, is it doing case-dependent stupid here? the filenames are all lowercase.

**Comment by bondskin** [comment]
Running https://github.com/influxdata/telegraf/pull/10748 keeps crashing & restarting Telegraf
```

● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
     Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-03-05 09:23:56 CET; 11s ago
       Docs: https://github.com/influxdata/telegraf
   Main PID: 24397 (telegraf)
      Tasks: 10 (limit: 1891)
        CPU: 13.467s
     CGroup: /system.slice/telegraf.service
             └─24397 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

Mar 05 09:23:56 raspberrypidns telegraf[24397]: 2022-03-05T08:23:56Z I! Loaded aggregators:
Mar 05 09:23:56 raspberrypidns telegraf[24397]: 2022-03-05T08:23:56Z I! Loaded processors:
Mar 05 09:23:56 raspberrypidns telegraf[24397]: 2022-03-05T08:23:56Z I! Loaded outputs: influxdb prometheus_client
Mar 05 09:23:56 raspberrypidns telegraf[24397]: 2022-03-05T08:23:56Z I! Tags enabled: host=raspberrypidns
Mar 05 09:23:56 raspberrypidns telegraf[24397]: 2022-03-05T08:23:56Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"raspberrypidns", Flus>
Mar 05 09:23:56 raspberrypidns systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Mar 05 09:24:04 raspberrypidns telegraf[24397]: Parse module: /var/lib/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Mar 05 09:24:04 raspberrypidns telegraf[24397]: 2022-03-05T08:24:04Z W! [inputs.snmp] Couldn't load module DPI20-MIB: Could not load module at DPI>
Mar 05 09:24:07 raspberrypidns telegraf[24397]: Parse module: /var/lib/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Mar 05 09:24:07 raspberrypidns telegraf[24397]: 2022-03-05T08:24:07Z W! [inputs.snmp] Couldn't load module HPR-MIB: Could not load module at HPR-M>
```



Going back to 1.21.2-1
still shows errors but Telegraf keeps running and not restarting
```
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
     Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-03-05 09:27:06 CET; 15s ago
       Docs: https://github.com/influxdata/telegraf
   Main PID: 26130 (telegraf)
      Tasks: 10 (limit: 1891)
        CPU: 17.093s
     CGroup: /system.slice/telegraf.service
             └─26130 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

Mar 05 09:27:06 raspberrypidns telegraf[26130]: 2022-03-05T08:27:06Z I! Loaded inputs: cpu disk (2x) diskio (2x) dns_query exec http internal kern>
Mar 05 09:27:06 raspberrypidns telegraf[26130]: 2022-03-05T08:27:06Z I! Loaded aggregators:
Mar 05 09:27:06 raspberrypidns telegraf[26130]: 2022-03-05T08:27:06Z I! Loaded processors:
Mar 05 09:27:06 raspberrypidns telegraf[26130]: 2022-03-05T08:27:06Z I! Loaded outputs: influxdb prometheus_client
Mar 05 09:27:06 raspberrypidns telegraf[26130]: 2022-03-05T08:27:06Z I! Tags enabled: host=raspberrypidns
Mar 05 09:27:06 raspberrypidns telegraf[26130]: 2022-03-05T08:27:06Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"raspberrypidns", Flus>
Mar 05 09:27:14 raspberrypidns telegraf[26130]: Parse module: /var/lib/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Mar 05 09:27:14 raspberrypidns telegraf[26130]: 2022-03-05T08:27:14Z W! [inputs.snmp] module DPI20-MIB could not be loaded
Mar 05 09:27:18 raspberrypidns telegraf[26130]: Parse module: /var/lib/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Mar 05 09:27:18 raspberrypidns telegraf[26130]: 2022-03-05T08:27:18Z W! [inputs.snmp] module HPR-MIB could not be loaded
```

Last good release without any SNMP errors for me is 1.20.4-1

**Comment by Hipska** [comment]
> Dumb thought, is it doing case-dependent stupid here? the filenames are all lowercase.

@bunnyevans Yes, I think that will actually be the case. The gosmi module expects files to be named like the snmp module name + optional extension like .my, .mib or .txt. See https://github.com/sleepinggenius2/gosmi/issues/34#issuecomment-1024538779

So until telegraf has implemented a method to track which MIBs need to be reevaluated after finding its dependencies, you will need to rename your files to workaround this.

**Comment by NickMacKechnie** [comment]
Hi All - when does the fix for this get pushed into apt update (sorry a newbie here)

**Comment by Hipska** [comment]
Next telegraf release 1.22 is planned for next week.

**Comment by bunnyevans** [comment]
> 

This works when "yamaha-smi.mib.txt" and friends are renamed to "YAMAHA-SMI.txt"
and nothing else. e.g. "YAMAHA-SMI-MIB.txt" does not work

I do not believe the specification includes filenames, so I await this being fixed.

**Comment by dmayan-ss** [comment]
This bug is still happening to me on 1.27.0

**Comment by Hipska** [comment]
Please open a new issue. This looks like a totally different bug.
