### ISSUE TITLE
Empty output for AWS/EBS and AWS/S3 

### ISSUE THREAD

**Issue by gugansankar** [influxdata/telegraf#1907]
I tried to pull AWS metrics through cloudwatch using telegraf and write the output data into influxdb.

When I run the test with sample config, it shows only EC2 stats . Not showing anything else.

For example, 
If I set the namespace to "AWS/EC2", then i can see the output,

]# telegraf -config telegraf.conf -input-filter cloudwatch -test

> cloudwatch_aws_ec2,host=gugan.ipt.local,region=us-east-1,unit=percent cpu_utilization_average=0.08,cpu_utilization_maximum=0.16,cpu_utilization_minimum=0,cpu_utilization_sample_count=2,cpu_utilization_sum=0.16 1476251580000000000
> cloudwatch_aws_ec2,host=gugan.ipt.local,image_id=ami-c481fad3,region=us-east-1,unit=bytes disk_write_bytes_average=0,disk_write_bytes_maximum=0,disk_write_bytes_minimum=0,disk_write_bytes_sample_count=2,disk_write_bytes_sum=0 1476251580000000000

If I changed namespace to EBS, it not showing any output
[root@gugan ~]# telegraf -config telegraf.conf -input-filter cloudwatch -test
- Plugin: cloudwatch, Collection 1
- Internal: 1m0s

[root@gugan ~]

Should I need to do any changes in AWS or else in Telegraf configuration ?.

Telegraf conf:
[[inputs.cloudwatch]]
   region = 'us-east-1'
   access_key = "xxxxxxxx"
   secret_key = "xxxxxxxxx"
   period = '1m'
   delay = '1m'
   interval = '1m'
   namespace = 'AWS/EBS'

**Comment by sparrc** [comment]
cc @joshglympse @johnrengelman

**Comment by kimor79** [comment]
I see similar behavior.

Here are the metrics that do end up in InfluxDB:
```
cloudwatch_aws_efs
cloudwatch_aws_elastic_beanstalk
cloudwatch_aws_elb
cloudwatch_aws_lambda
cloudwatch_aws_rds
```

Config:
```
[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/ApplicationELB'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/AutoScaling'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/DynamoDB'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/EC2'
  [[inputs.cloudwatch.metrics]]
    names = [ 'CPUCreditBalance', 'CPUCreditUsage', 'StatusCheckFailed', 'StatusCheckFailed_Instance', 'StatusCheckFailed_System' ]
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/ElasticBeanstalk'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/EFS'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/ELB'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/ElasticMapReduce'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/Kinesis'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/Lambda'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/Redshift'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/RDS'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/SNS'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/SQS'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'

[[inputs.cloudwatch]]
  role_arn = 'arn:aws:iam::MYACCOUNT:role/MYROLE'
  region = 'us-east-1'
  period = '1m'
  delay = '60m'
  interval = '60m'
  namespace = 'AWS/S3'
  [inputs.cloudwatch.tags]
    aws_account = 'MYACCOUNT'
```

**Comment by johnrengelman** [comment]
@kimor79 can you try setting 'period=5m' and see if that makes a difference?

**Comment by kimor79** [comment]
I changed AutoScaling, the second input, to 5m but it didn't make a difference:

```
* Plugin: cloudwatch, Collection 1
* Internal: 3m0s
* Plugin: cloudwatch, Collection 1
* Internal: 3m0s
* Plugin: cloudwatch, Collection 1
* Internal: 3m0s
* Plugin: cloudwatch, Collection 1
* Internal: 3m0s
* Plugin: cloudwatch, Collection 1
* Internal: 3m0s
> cloudwatch_aws_elastic_beanstalk,aws_account=MYACCOUNT,environment_name=MYBEANSTALK,region=us-east-1,unit=none environment_health_average=0,environment_health_maximum=0,environment_health_minimum=0,environment_health_sample_count=1,environment_health_sum=0 1477524960000000000
```

**Comment by sparrc** [comment]
@kimor79 @gugansankar can you confirm that this behavior is observed when not in `--test` mode?

@kostasb I remember you mentioned a customer issue with this, did you ever track it down?

**Comment by kimor79** [comment]
Yes, I can confirm the behavior when not in `--test`

**Comment by johnrengelman** [comment]
@kimor79 Autoscaling metrics are not enabled by default in AWS accounts. Have you enabled them for some ASGs? (http://docs.aws.amazon.com/autoscaling/latest/userguide/as-instance-monitoring.html#as-enable-group-metrics)

If you have not enabled them for any ASG, then cloudwatch returns an empty list of metrics available for the AWS/AutoScaling namespace.

That might be the issue there...i'm looking into other issues as there have been a few reports.

**Comment by johnrengelman** [comment]
@gugansankar can you change your single quotes `'` to double quotes `"` in your config file and try again?

**Comment by kimor79** [comment]
Good catch with the autoscaling metrics. It was indeed not having metrics enabled in AWS.

**Comment by johnrengelman** [comment]
@sparrc Still waiting for feeback, but this might just be a configuration issue - I've fixed up some docs here: https://github.com/influxdata/telegraf/pull/1991

**Comment by johnrengelman** [comment]
Some more info that is likely pertinent: https://github.com/influxdata/telegraf/issues/1574#issuecomment-258337777

**Comment by sparrc** [comment]
@johnrengelman It sounds like we probably need to update the documentation with this information....do you think you could submit a PR for that?

**Comment by johnrengelman** [comment]
For sure. Will do it later this morning.

**Comment by kimor79** [comment]
I've been trying various period/interval combinations and so far these ones still don't record any metrics (even though there are metrics in CloudWatch):

EC2 (and I'm only interested in a subset: 'CPUCreditBalance', 'CPUCreditUsage', 'StatusCheckFailed', 'StatusCheckFailed_Instance', 'StatusCheckFailed_System')
SNS
S3

**Comment by antoiner77** [comment]
Same problem with the last version, 
Config:
```
[agent]
interval = "1m"
[[outputs.influxdb]]
  urls = ["http://localhost:8086"] # required
  database = "telegraf" # required
  retention_policy = ""
  write_consistency = "any"
  timeout = "10s"

[[inputs.cloudwatch]]
  region = "eu-west-1"
  period = "5m"
  delay = "5m"
  interval = "5m"
  ratelimit = 10
  namespace = "AWS/S3"

  [[inputs.cloudwatch.metrics]]
    names = ["BucketSizeBytes"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "BucketName"
      value = "xxx"
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "StorageType"
      value = "StandardStorage"
```
If this can help..
I have try the double/single quotes things, change period delay and interval with no success

**Comment by jacobtomlinson** [comment]
Would be great to get an update on this. I'm also seeing the same issue when trying to get S3 metrics.

**Comment by internaught** [comment]
Same issue here... No EC2 stats are coming out...

```
/usr/bin/telegraf -config cloudwatch.conf -input-filter cloudwatch -test
* Plugin: inputs.cloudwatch, Collection 1
* Internal: 10m0s
```

**Comment by danielnelson** [comment]
These S3 metrics are [daily](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/s3-metricscollected.html), so you need to set your period to "24h".  I'll clarify this in the documentation.

**Comment by jacobtomlinson** [comment]
Changing to period to `24h` has not resolved the issue. Do I need to change anything else too?

```
[[inputs.cloudwatch]]
  region = "eu-west-1"
  period = "24h"
  delay = "5m"
  interval = "5m"
  namespace = "AWS/S3"
  ratelimit = 10

  [[inputs.cloudwatch.metrics]]
    names = ["BucketSizeBytes"]
```

**Comment by danielnelson** [comment]
Try removing the metrics subtable, here is the config I used:
```
[[inputs.cloudwatch]]
  region = "us-west-2"
  period = "24h"
  delay = "5m"
  interval = "5m"
  namespace = "AWS/S3"
  ratelimit = 200
```

**Comment by jacobtomlinson** [comment]
@danielnelson That did it! Thanks very much.

**Comment by Nagarjuna586** [comment]
Hello All, 

I am also getting the same issue. I Am trying to get the cloud watch metrics from aws. below is the o/p i am getting when i test. also i am getting the empty measurements.

Telegraf version:
Telegraf v1.3.4 (git: release-1.3 7bbd3daa98d5931c6e9025a98105092b0722de0d)

Below is the configuration:
[[inputs.cloudwatch]]
  access_key = 'XXXXXXXXXXXXXXXXXXXXX'
  secret_key = 'XXXXXXXXXXXXXXXXXXXXX'
  region = 'us-east-1'
  period = '1m'
  delay = '3m'
  interval = '3m'
  namespace = 'AWS/EC2'
  [[inputs.cloudwatch.metrics]]
    names = [ 'CPUCreditBalance', 'CPUCreditUsage', 'StatusCheckFailed', 'StatusCheckFailed_Instance', 'StatusCheckFailed_System' ]

Similarly I fallowed for ELB & IoT.

Output:
 * Plugin: inputs.cloudwatch, Collection 1
* Internal: 5m0s
* Plugin: inputs.cloudwatch, Collection 1
* Internal: 5m0s
* Plugin: inputs.cloudwatch, Collection 1
* Internal: 3m0s

Please advice on this.

**Comment by danielnelson** [comment]
@Nagarjuna586 Make sure you are using the correct period for the metrics.  Based on https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ec2-metricscollected.html the CPU metrics are only available in 5m periods, while the Status metrics are available in 1m periods.

You will need a separate input for each period.  Start out by setting the period, delay, and interval options all to the value of this period.

Lastly, add in the metrics table as a second step after you have verified it is working without it.

```toml
[[inputs.cloudwatch]]
  access_key = 'XXXXXXXXXXXXXXXXXXXXX'
  secret_key = 'XXXXXXXXXXXXXXXXXXXXX'
  region = 'us-east-1'
  period = '5m'
  delay = '5m'
  interval = '5m'
  namespace = 'AWS/EC2'

[[inputs.cloudwatch]]
  access_key = 'XXXXXXXXXXXXXXXXXXXXX'
  secret_key = 'XXXXXXXXXXXXXXXXXXXXX'
  region = 'us-east-1'
  period = '1m'
  delay = '1m'
  interval = '1m'
  namespace = 'AWS/EC2'
```

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
