### ISSUE TITLE
FreeBSD - Telegraf restarts and eventually fails

### ISSUE THREAD

**Issue by billyhudson** [influxdata/telegraf#4583]
### Relevant telegraf.conf:

```
[global_tags]

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "5s"
  flush_interval = "60s"
  flush_jitter = "10s"
  precision = ""
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = "main-test-app1"
  omit_hostname = false

[[outputs.influxdb]]
urls = ["https://test-influx-db.example.com:443"]
  database = "telegraf"
  retention_policy = ""
  write_consistency = "any"
  timeout = "10s"
  username = "writer"
  password = "examplepassword"


[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
  mount_points = ["/"]

[[inputs.diskio]]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.processes]]

[[inputs.system]]

[[inputs.net]]
```

### Logs:
Telegraf is configured to log to /var/log/telegraf/telegraf.log but the SIGQUIT go trace always outputs to /var/log/telegraf.log
[telegraf.telegraf.log](https://github.com/influxdata/telegraf/files/2310236/telegraf.telegraf.log)
[telegraf.log](https://github.com/influxdata/telegraf/files/2310237/telegraf.log)

### System info:
FreeBSD 11.1-RELEASE-p10
telegraf-1.6.3

### Description:

One of the 6 instances communicating to our InfluxDB occasionally fails at random times.
All instances are running the same version of telegraf and varying versions of FreeBSD.

```
main-test-app1:~ # uname -r 11.1-RELEASE-p10 <- troublesome instance
main-test-cache1~]$ uname -r 11.1-RELEASE-p4
proj1-test-app1 ~]$ uname -r 11.2-RELEASE-p2
test-influx-app:~ # uname -r 11.2-RELEASE-p2
test-influx-db:~ # uname -r 11.2-RELEASE-p2 <- our influxdb server
proj2-test-app1:~ # uname -r 11.2-RELEASE-p1
proj2-test-db1 ~]$ uname -r 11.2-RELEASE-p1
```

Telegraf will start, write metrics successfully for some time and then Telegraf appears to restart as obvious by the Telegraf startup text being reprinted and the child process started by the daemon changing PID. 
This is only happening on our main-test-app1 instance.
Occasionally this will restart fine with a minute of metrics missing but sometimes Telegraf would freeze completely and fail to restart, I would then have to manually stop the Telegraf service.
In previous troubleshooting attempts certain plugins have failed to collect where others have succeeded, showing the ` took longer to collect than collection interval ` error message, however this has not happened on this occasion and has been inconsistent in which plugins would fail.

Ive tried increasing the flush interval and lowering the amount of input plugins that are running in an attempt to localize the issue to a particular plugin.

### Steps to reproduce:

1. Install telegraf-1.6.3 via pkg on FreeBSD11.1.
2. Create config based on above telegraf.conf
3. Run until failure.

### Expected behavior:

Telegraf will succesfully communicate metrics to InfluxDB server.

### Actual behavior:

Telegraf eventually fails to communicate metrics to InfluxDB server.

**Comment by danielnelson** [comment]
I am going to guess that the different log file is caused by Telegraf logging the panic stack trace to stderr instead of using the agents logfile.

The actual crash, `fatal error: runtime: split stack overflow`, seems like it could be an error in Go.  I did find an issue but it has been fixed for some time https://github.com/golang/go/issues/14067

@girgen Do you know what version of Go is used in this package?

**Comment by girgen** [comment]
@danielnelson go-1.10.2 is the most likely candidate.

pkg building is automated in FreeBSD, so it actually depends a bit. Telegraf-1.6.3 was committed 2018-05-25  and at that time go-1.10.2 was in the tree, so telegraf package would have been built with that version of go.

The latest version of telegraf in the FreeBSD tree is telegraf-1.7.3 which should have been build using go-1.10.3

**Comment by danielnelson** [comment]
@billyhudson Would it be possible for you to check if the crash remains in 1.7.3?

**Comment by billyhudson** [comment]
I have upgraded the telegraf package to 1.7.3 and started the service, shall report back, thank you.

**Comment by billyhudson** [comment]
It still appears to be crashing but with a different go trace, however I've noticed it has had more success at recovering.

[telegraf-20180824.log](https://github.com/influxdata/telegraf/files/2318684/telegraf-20180824.log)

**Comment by danielnelson** [comment]
That is quite the assortment of errors, all from within the Go runtime:
```
fatal error: newproc1: new g is not Gdead
fatal error: findrunnable: negative nmspinning
fatal error: bad g->status in ready
fatal error: workbuf is empty
```

Do you have multiple systems all reporting similar errors or is this all from a lone server?  I have seen similar behavior in Linux that has been traced back to a hardware issue.

**Comment by billyhudson** [comment]
This is only happening on one of our T2.medium servers at aws, of which there is another in the same region that is absolutely fine.

**Comment by danielnelson** [comment]
I'm going to close this issue with the recommendation to replace this AWS instance as it is not working properly.

**Comment by billyhudson** [comment]
After reinstalling all base packages and stopping and starting the instance at AWS, destroying and recreating this instance appears to have resolved the problem. Thank you.
