### ISSUE TITLE
Provide a tar.gz release package for Darwin / MacOS with CGO

### ISSUE THREAD

**Issue by itzg** [influxdata/telegraf#4801]
### Proposal:

It would be very helpful to obtain the "tar.gz" binary packages for Darwin under https://github.com/influxdata/telegraf/releases/latest .

### Current behavior:

At a particular release area, such as ["latest",](https://github.com/influxdata/telegraf/releases/latest), there are many platforms listed, but Darwin is not one of them.

### Desired behavior:

See a tar.gz binary package for Darwin-amd64 as a platform choice in the releases.

### Use case:

We are building a tool that automates installation of Telegraf on user devices and having a unified way of downloading and extracting the pre-built binary bundle on Linux, Windows, and MacOS would avoid one-off conditional code for MacOS devices. Right now the one-off code has to access the binaries via [Homebrew's repo](https://homebrew.bintray.com/bottles/telegraf-1.8.0.high_sierra.bottle.tar.gz) where the structure of that package is inconsistent with the official packages.

**Comment by danielnelson** [comment]
I wonder which files should go into the darwin tar.gz?  Do you think it should just be telegraf and telegraf.conf similar to the Windows zip files?

**Comment by itzg** [comment]
Yes, I think the two files like the Windows zip would be perfect.

**Comment by goller** [comment]
Hey @itzg , I've just merged in a change that will create darwin builds for the upcoming 1.12 release.

**Comment by itzg** [comment]
@goller sorry to comment on a closed issue, but I gave the Darwin/MacOSX binaries a try and am running into the issue reported in https://github.com/influxdata/telegraf/issues/1484 where I see the following when configuring a CPU input plugin with no specific fields set:

```
E! [inputs.cpu] Error in plugin: error getting CPU info: not implemented yet
```

**Comment by danielnelson** [comment]
The issue is that the Darwin build requires CGO for the cpu plugin, and possible other key plugins.  As the packages are cross compiled from Linux, they do not have CGO enabled.

I'm not sure how feasible a non-cgo implementation would be for Darwin, but it might be possible to add one to gopsutil, outside of that we could look into using a Darwin build machine on CircleCI.

Reopening the issue since, even though technically we have the package, it's probably not usable by most who would be interested in it.

**Comment by jimmyseto** [comment]
> The issue is that the Darwin build requires CGO for the cpu plugin, and possible other key plugins. As the packages are cross compiled from Linux, they do not have CGO enabled.
> 
> I'm not sure how feasible a non-cgo implementation would be for Darwin, but it might be possible to add one to gopsutil, outside of that we could look into using a Darwin build machine on CircleCI.
> 
> Reopening the issue since, even though technically we have the package, it's probably not usable by most who would be interested in it.

@danielnelson - what's the current status of this?  are there plans to use a Darwin build machine to make the posted packages more usable?  thanks in advance.

**Comment by donalod** [comment]
Hello, also curious as running telegraf 1.16.2 on OSX 10.11.6 wth go1.11 and still getting "[inputs.cpu] Error in plugin: error getting CPU info: not implemented yet"

**Comment by ssoroka** [comment]
As a work around for this until we add a new release package, you can build Telegraf yourself with CGO enabled like so: `env CGO_ENABLED=1 go build ./cmd/telegraf`

**Comment by ssoroka** [comment]
going to close this in favor of https://github.com/influxdata/telegraf/issues/8837, as it's more in-line with the approach we want to be taking. (going down the road of supporting CGO everywhere would be painful: it would double the build times and use of CGO is not a simple one-binary deploy).

**Comment by jimmyseto** [comment]
> going to close this in favor of #8837, as it's more in-line with the approach we want to be taking. (going down the road of supporting CGO everywhere would be painful: it would double the build times and use of CGO is not a simple one-binary deploy).

@ssoroka - even with a fix for #8837, users would still need to either build their own macOS binaries or go through Homebrew, correct?

**Comment by Hipska** [comment]
There is an official build on the releases page.

**Comment by jimmyseto** [comment]
> There is an official build on the releases page.

oh right.  i've been resorting to homebrew and/or build-your-own for so long now, i completely forgot about that!  thanks.
