### ISSUE TITLE
After upgrade to 1.15.3 => [inputs.vsphere] Error in plugin: while collecting vm: ServerFaultCode: XML document element count exceeds configured maximum 500000

### ISSUE THREAD

**Issue by BenoitPoulet** [influxdata/telegraf#8169]
### Relevant telegraf.conf:

```toml
[[inputs.vsphere]]
  interval = "300s"
  vcenters = [ "https://1/sdk", "https://2/sdk" ]
  username = "yy"
  password = "xx"
    max_query_objects = 64
    max_query_metrics = 64
   collect_concurrency = 5
   discover_concurrency = 2
    object_discovery_interval = "1800s"
    timeout = "120s"
    insecure_skip_verify = true

  [inputs.vsphere.tags]
    tag1 = "vsphere"
```

### System info:
Debian 9.13
Telegraf 1.15.3

### Steps to reproduce:

1. Have a Telegraf 1.14.3 running fine with this config
2. Upgrade Telegraf to 1.15.3
3. Errors in the log files, one of the Vcenter data are no longer inserted into the DB

### Additional info:
The Vcenter who is impacted has the version : 6.5.0.13000

Roll back to version 1.14.3 solved the problem.

Debug log :

```
2020-09-22T16:20:35Z E! [inputs.vsphere] Error in plugin: while collecting cluster: ServerFaultCode: This operation is restricted by the administrator - 'vpxd.stats.maxQueryMetrics'. Contact your system administrator.
2020-09-22T16:20:35Z D! [inputs.vsphere] Query for cluster has 1 QuerySpecs
2020-09-22T16:20:36Z D! [inputs.vsphere] Query for cluster returned metrics for 21 objects
2020-09-22T16:20:36Z D! [inputs.vsphere] CollectChunk for cluster returned 63 metrics
2020-09-22T16:20:36Z D! [inputs.vsphere] CollectChunk for cluster returned 63 metrics
2020-09-22T16:20:36Z D! [inputs.vsphere] Query for cluster has 1 QuerySpecs
2020-09-22T16:20:36Z D! [inputs.vsphere] CollectChunk for vm returned 0 metrics
2020-09-22T16:20:36Z E! [inputs.vsphere] Error in plugin: while collecting vm: ServerFaultCode: XML document element count exceeds configured maximum 500000

while parsing property "counterId" of static type int

while parsing serialized DataObject of type vim.PerformanceManager.MetricId
at line 2, column 11453111

while parsing property "metricId" of static type ArrayOfPerfMetricId

while parsing serialized DataObject of type vim.PerformanceManager.QuerySpec
at line 2, column 11452458

while parsing call information for method QueryPerf
at line 2, column 66

while parsing SOAP body
at line 2, column 60

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request for method queryStats
on object of type vim.PerformanceManager
at line 1, column 0
2020-09-22T16:20:36Z D! [inputs.vsphere] Latest sample for vm set to 0001-01-01 00:00:00 +0000 UTC
2020-09-22T16:20:36Z D! [inputs.vsphere] Query for cluster returned metrics for 1 objects
2020-09-22T16:20:36Z D! [inputs.vsphere] CollectChunk for cluster returned 27 metrics
```

**Comment by ssoroka** [comment]
cc @prydin

**Comment by mikkoss** [comment]
hi,
We seem to be hitting the same bug but with vsphere 6.7 version. Any progress with this? Upgraded from  telegraf-1.14.5-1.x86_64 ->1.15.3-1 today. Reverting back to old, but if needed I can reupgrade.

2020-10-05T10:33:08Z E! [inputs.vsphere] Error in plugin: while collecting vm: ServerFaultCode: XML document element count exceeds configured maximum 500000

while parsing property "counterId" of static type int

while parsing serialized DataObject of type vim.PerformanceManager.MetricId
at line 2, column 11453964

while parsing property "metricId" of static type ArrayOfPerfMetricId

while parsing serialized DataObject of type vim.PerformanceManager.QuerySpec
at line 2, column 11453312

while parsing call information for method QueryPerf
at line 2, column 66

while parsing SOAP body
at line 2, column 60

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request for method queryStats
on object of type vim.PerformanceManager

**Comment by prydin** [comment]
Could you please run telegraf with the -debug option and send me the log?

**Comment by prydin** [comment]
Does this happen just the first round of metric collection or does it happen all the time? Also, how many VMs do you have in that environment?

**Comment by BenoitPoulet** [comment]
For me, all the time.
I have around 2800 Vms on 2 Vcenters.

**Comment by prydin** [comment]
OK. I have an idea what might be going on. I'll try to get a patched version up later today.

**Comment by mikkoss** [comment]
All the time (I let it run about 5 minutes @1min collection cycle. before downgrade) 4 vcenters collected, biggest has about 1200VM's. 2 vcenters running 6.5 version it seems and 2 bigger running 6.7 version.

Another error that keeps repeating is :
2020-10-05T13:55:28Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!
Over 6000 of these in log for 5 minutes

There are 5:
2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for vm returned 0 metrics
2020-10-05T13:55:29Z E! [inputs.vsphere] Error in plugin: while collecting vm: ServerFaultCode: XML document element count exceeds configured maximum 500000

So it seems to be from 1 vcenter only,  If needed I can clean up the config to collect this one vcenter only with debug settings.

Here is a bit larger snipping of error logs: Unfortunately it's not clear which vcenter gives the error but biggest one wast the one with missing grapshs.

2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for cluster returned 21 metrics
2020-10-05T13:55:29Z D! [inputs.vsphere] Latest sample for cluster set to 2020-10-05 13:55:00 +0000 UTC
2020-10-05T13:55:29Z D! [inputs.vsphere] purged timestamp cache. 0 deleted with 18 remaining
2020-10-05T13:55:29Z D! [inputs.vsphere] Query for cluster returned metrics for 1 objects
2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for cluster returned 30 metrics
2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for cluster returned 30 metrics
2020-10-05T13:55:29Z D! [inputs.vsphere] Query for cluster has 1 QuerySpecs
2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for cluster returned 0 metrics
2020-10-05T13:55:29Z E! [inputs.vsphere] Error in plugin: while collecting cluster: ServerFaultCode: This operation is restricted by the administrator - 'vpxd.stats.maxQueryMetrics'. Contact your system administrator.
2020-10-05T13:55:29Z D! [inputs.vsphere] Query for cluster has 1 QuerySpecs
2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for cluster returned 0 metrics
2020-10-05T13:55:29Z E! [inputs.vsphere] Error in plugin: while collecting cluster: ServerFaultCode: This operation is restricted by the administrator - 'vpxd.stats.maxQueryMetrics'. Contact your system administrator.
2020-10-05T13:55:29Z D! [inputs.vsphere] Query for cluster has 1 QuerySpecs
2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for vm returned 0 metrics
2020-10-05T13:55:29Z E! [inputs.vsphere] Error in plugin: while collecting vm: ServerFaultCode: XML document element count exceeds configured maximum 500000

while parsing property "counterId" of static type int

while parsing serialized DataObject of type vim.PerformanceManager.MetricId
at line 2, column 11453950

while parsing property "metricId" of static type ArrayOfPerfMetricId

while parsing serialized DataObject of type vim.PerformanceManager.QuerySpec
at line 2, column 11453300

while parsing call information for method QueryPerf
at line 2, column 66

while parsing SOAP body
at line 2, column 60

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request for method queryStats
on object of type vim.PerformanceManager
at line 1, column 0
2020-10-05T13:55:29Z D! [inputs.vsphere] Latest sample for vm set to 0001-01-01 00:00:00 +0000 UTC
2020-10-05T13:55:29Z D! [inputs.vsphere] Query for vm returned metrics for 161 objects
2020-10-05T13:55:29Z D! [inputs.vsphere] Query for cluster returned metrics for 1 objects
2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for cluster returned 21 metrics
2020-10-05T13:55:29Z D! [inputs.vsphere] CollectChunk for cluster returned 21 metrics

**Comment by BenoitPoulet** [comment]
>Another error that keeps repeating is :
>2020-10-05T13:55:28Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!

I also had this error with 1.15.3 (but on another ID ofc)

**Comment by prydin** [comment]
Hi! Sorry for the delay. I've applied a fix to this issue. There was a bug in the counting of metrics sent causing the buffer to grow too large under certain circumstances. I've tried it on the largest vCenter I could find, but I'd appreciate it if you could test it against your environment to verify that the issue is resolved. Here's a pre-release: https://github.com/prydin/telegraf/releases/tag/ISSUE-8169

It's only a Linux binary for now. Let me know if you need other binaries, and I'll upload them as well.

**Comment by prydin** [comment]
@mikkoss I'm not sure I understand whether the shorter discovery time took care of the missing metric errors. That message is probably benign and means that a certain metric isn't recorded for some resources. I'll dig a little deeper and try to figure out exactly which metric it is.

As for the 1291 object, this refers to the total number of VMs managed by this vCenter, not just a cluster. It probably just means that you have multiple cluster with a total of 1291 VMs in them.

"Found 148 metrics" just means that it found 148 different types of metrics for a particular resource. It should repeat for every resource with very small variations.

**Comment by mikkoss** [comment]
Hi,

unfortunately new discovery did not fix the error it still keeps coming and filling the logs.  I'll have to  modify our config a bit to have all different vcenters in their own files, so that I can select more easily which are polled for debug info and for --test runs. Default logging identifier "inputs.vsphere" is annoying as we have 8 different collectors for vsphere... It would make debugging much easier if log's would include the vcenter name which gives the log message not just generic inputs.vsphere. 

I did have some time to look of the grafana graphs and they did look good. But as we do have plenty of vm's it was just random few that I checked.

**Comment by mikkoss** [comment]
If it helps I now have debug level logs from old version and new version here are snippets where the errors begin: config has 2 collections for the same vcenter one for 1minute data and one for 5 minutes. (as in default instructions to collect those non realtime statistics)

for the old version log of 2 collection cycles is 600 lines and new has 5846 lines 

New build:
2020-10-29T15:25:19Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2020-10-29T15:25:25Z D! [inputs.vsphere] Interval estimated to 1m0s
2020-10-29T15:25:25Z D! [inputs.vsphere] Collecting metrics for 1198 objects of type vm for vcenter-name-here
2020-10-29T15:25:25Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 147
2020-10-29T15:25:25Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 294
2020-10-29T15:25:25Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 441
2020-10-29T15:25:25Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 588
2020-10-29T15:25:25Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 735
2020-10-29T15:25:25Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!
and these keep on coming
missing linesx
2020-10-29T15:25:25Z D! [inputs.vsphere] Interval estimated to 1m0s
2020-10-29T15:25:25Z D! [inputs.vsphere] Collecting metrics for 2 objects of type datacenter for vcenter-name-here
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 20
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 40
2020-10-29T15:25:25Z D! [inputs.vsphere] Submitting job for datacenter: 2 objects, 40 metrics
missing lines
2020-10-29T15:25:25Z D! [inputs.vsphere] Query for datacenter returned metrics for 2 objects
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 38808
2020-10-29T15:25:25Z I! [inputs.vsphere] Unable to find metric name for id 452. Skipping!
2020-10-29T15:25:25Z D! [inputs.vsphere] CollectChunk for datacenter returned 120 metrics
2020-10-29T15:25:25Z D! [inputs.vsphere] CollectChunk for datacenter returned 120 metrics
2020-10-29T15:25:25Z D! [inputs.vsphere] Latest sample for datacenter set to 2020-10-29 15:25:00 +0000 UTC
2020-10-29T15:25:25Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 38955


old version:

2020-10-29T15:28:30Z D! [inputs.vsphere] Collecting metrics for 1198 objects of type vm for vcenter-name-here
2020-10-29T15:28:30Z D! [inputs.vsphere] Queueing query: 257 objects, 38036 metrics (0 remaining) of type vm for vcenter-name-here. Processed objects: 257. Total objects 1198
2020-10-29T15:28:30Z D! [inputs.vsphere] Queueing query: 256 objects, 37888 metrics (0 remaining) of type vm for vcenter-name-here. Processed objects: 513. Total objects 1198
2020-10-29T15:28:30Z D! [inputs.vsphere] Query for vm has 257 QuerySpecs
2020-10-29T15:28:30Z D! [inputs.vsphere] Queueing query: 256 objects, 37888 metrics (0 remaining) of type vm for vcenter-name-here. Processed objects: 769. Total objects 1198
2020-10-29T15:28:30Z D! [inputs.vsphere] Queueing query: 256 objects, 37888 metrics (0 remaining) of type vm for vcenter-name-here. Processed objects: 1025. Total objects 1198
2020-10-29T15:28:30Z D! [inputs.vsphere] Queuing query: 173 objects, 25604 metrics (0 remaining) of type vm for vcenter-name-here. Total objects 1198 (final chunk)
2020-10-29T15:28:30Z D! [inputs.vsphere] Interval estimated to 1m0s
2020-10-29T15:28:30Z D! [inputs.vsphere] Collecting metrics for 2 objects of type datacenter for vcenter-name-here
2020-10-29T15:28:30Z D! [inputs.vsphere] Queuing query: 2 objects, 40 metrics (0 remaining) of type datacenter for vcenter-name-here. Total objects 2 (final chunk)
2020-10-29T15:28:30Z D! [inputs.vsphere] Query for datacenter has 2 QuerySpecs
2020-10-29T15:28:30Z D! [inputs.vsphere] Interval estimated to 1m0s
2020-10-29T15:28:30Z D! [inputs.vsphere] Collecting metrics for 37 objects of type host for vcenter-name-here
2020-10-29T15:28:30Z D! [inputs.vsphere] Queuing query: 37 objects, 7548 metrics (0 remaining) of type host for vcenter-name-here. Total objects 37 (final chunk)
2020-10-29T15:28:30Z D! [inputs.vsphere] Query for host has 37 QuerySpecs
2020-10-29T15:28:30Z D! [inputs.vsphere] Query for datacenter returned metrics for 2 objects
2020-10-29T15:28:30Z D! [inputs.vsphere] CollectChunk for datacenter returned 120 metrics
2020-10-29T15:28:30Z D! [inputs.vsphere] Latest sample for datacenter set to 2020-10-29 15:25:00 +0000 UTC
2020-10-29T15:28:32Z D! [outputs.influxdb] Wrote batch of 8 metrics in 53.425794ms

**Comment by prydin** [comment]
@mikkoss What's your vCenter version?

**Comment by mikkoss** [comment]
This is 6.7u3 latest  build.

**Comment by mikkoss** [comment]
@prydin that was the fix it seems. 
With debug logging and running only the big vcenter server with the new binary I get only a huge number of:

2020-11-02T16:02:42Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 28268
2020-11-02T16:02:42Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 28416
2020-11-02T16:02:42Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 28564
2020-11-02T16:02:42Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 28712
2020-11-02T16:02:42Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 28860
2020-11-02T16:02:42Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 29008
2020-11-02T16:02:42Z D! [inputs.vsphere] Added bucket. Total buffered queries is now 29156

and there are no more the errors for the ID 452 Skipping! So looks good now.
I'll test this in production tomorrow so that it collects all the vcenters with our default configs. Now it was limited to only this one vcenter.

Thanks for fixing the issue.

**Comment by prydin** [comment]
@mikkoss Yeah, those are temporary debug statements that I will remove in the final version.

**Comment by mikkoss** [comment]
I have been using this latest head version now for a day to collect all vsphere stats. No problems seen vsphere graphs work nicely. 
Thanks again for the fix of the issue.

**Comment by sjwang90** [comment]
Fixed in #8357
